architect:
- isgarlo
docker:
  image: yegor256/java8
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
merge:
  script: |-
    mvn clean install --errors --settings ../settings.xml
  commanders:
  - isgarlo
deploy:
  script: |-
    mvn clean deploy --errors --settings ../settings.xml
  commanders:
  - isgarlo
release:
  pre: false
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pgivemeadriver --errors --settings ../settings.xml
  commanders:
  - isgarlo
